name: Build Docker Images
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push docker images
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup Docker Metadata
      id: docker_metadata
      uses: docker/metadata-action@v4.4.0
      with:
        images: catalystcoop/pudl-output-differ
        flavor: latest=auto
        tags: |
          type=sha,prefix={{branch}}-
          type=raw,value=latest-{{branch}}
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max